//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:ReceiptAdvice-2")]
[System.Xml.Serialization.XmlRootAttribute("ReceiptAdvice", Namespace="urn:oasis:names:specification:ubl:schema:xsd:ReceiptAdvice-2", IsNullable=false)]
public partial class ReceiptAdviceType {
    
    private UBLExtensionType[] uBLExtensionsField;
    
    private UBLVersionIDType uBLVersionIDField;
    
    private CustomizationIDType customizationIDField;
    
    private ProfileIDType profileIDField;
    
    private IDType idField;
    
    private CopyIndicatorType copyIndicatorField;
    
    private UUIDType uUIDField;
    
    private IssueDateType issueDateField;
    
    private IssueTimeType issueTimeField;
    
    private ReceiptAdviceTypeCodeType receiptAdviceTypeCodeField;
    
    private NoteType[] noteField;
    
    private LineCountNumericType lineCountNumericField;
    
    private OrderReferenceType[] orderReferenceField;
    
    private DocumentReferenceType despatchDocumentReferenceField;
    
    private DocumentReferenceType[] additionalDocumentReferenceField;
    
    private SignatureType[] signatureField;
    
    private CustomerPartyType deliveryCustomerPartyField;
    
    private SupplierPartyType despatchSupplierPartyField;
    
    private CustomerPartyType buyerCustomerPartyField;
    
    private SupplierPartyType sellerSupplierPartyField;
    
    private ShipmentType shipmentField;
    
    private ReceiptLineType[] receiptLineField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Xml.Serialization.XmlArrayItemAttribute("UBLExtension", IsNullable=false)]
    public UBLExtensionType[] UBLExtensions {
        get {
            return this.uBLExtensionsField;
        }
        set {
            this.uBLExtensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public UBLVersionIDType UBLVersionID {
        get {
            return this.uBLVersionIDField;
        }
        set {
            this.uBLVersionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public CustomizationIDType CustomizationID {
        get {
            return this.customizationIDField;
        }
        set {
            this.customizationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public ProfileIDType ProfileID {
        get {
            return this.profileIDField;
        }
        set {
            this.profileIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public IDType ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public CopyIndicatorType CopyIndicator {
        get {
            return this.copyIndicatorField;
        }
        set {
            this.copyIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public UUIDType UUID {
        get {
            return this.uUIDField;
        }
        set {
            this.uUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public IssueDateType IssueDate {
        get {
            return this.issueDateField;
        }
        set {
            this.issueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public IssueTimeType IssueTime {
        get {
            return this.issueTimeField;
        }
        set {
            this.issueTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public ReceiptAdviceTypeCodeType ReceiptAdviceTypeCode {
        get {
            return this.receiptAdviceTypeCodeField;
        }
        set {
            this.receiptAdviceTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public NoteType[] Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public LineCountNumericType LineCountNumeric {
        get {
            return this.lineCountNumericField;
        }
        set {
            this.lineCountNumericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderReference", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public OrderReferenceType[] OrderReference {
        get {
            return this.orderReferenceField;
        }
        set {
            this.orderReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public DocumentReferenceType DespatchDocumentReference {
        get {
            return this.despatchDocumentReferenceField;
        }
        set {
            this.despatchDocumentReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdditionalDocumentReference", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public DocumentReferenceType[] AdditionalDocumentReference {
        get {
            return this.additionalDocumentReferenceField;
        }
        set {
            this.additionalDocumentReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public SignatureType[] Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public CustomerPartyType DeliveryCustomerParty {
        get {
            return this.deliveryCustomerPartyField;
        }
        set {
            this.deliveryCustomerPartyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public SupplierPartyType DespatchSupplierParty {
        get {
            return this.despatchSupplierPartyField;
        }
        set {
            this.despatchSupplierPartyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public CustomerPartyType BuyerCustomerParty {
        get {
            return this.buyerCustomerPartyField;
        }
        set {
            this.buyerCustomerPartyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public SupplierPartyType SellerSupplierParty {
        get {
            return this.sellerSupplierPartyField;
        }
        set {
            this.sellerSupplierPartyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public ShipmentType Shipment {
        get {
            return this.shipmentField;
        }
        set {
            this.shipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReceiptLine", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
    public ReceiptLineType[] ReceiptLine {
        get {
            return this.receiptLineField;
        }
        set {
            this.receiptLineField = value;
        }
    }
}