//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
[System.Xml.Serialization.XmlRootAttribute("AllowanceCharge", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", IsNullable=false)]
public partial class AllowanceChargeType {
    
    private ChargeIndicatorType chargeIndicatorField;
    
    private AllowanceChargeReasonType allowanceChargeReasonField;
    
    private MultiplierFactorNumericType multiplierFactorNumericField;
    
    private SequenceNumericType sequenceNumericField;
    
    private AmountType2 amountField;
    
    private BaseAmountType baseAmountField;
    
    private PerUnitAmountType perUnitAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public ChargeIndicatorType ChargeIndicator {
        get {
            return this.chargeIndicatorField;
        }
        set {
            this.chargeIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public AllowanceChargeReasonType AllowanceChargeReason {
        get {
            return this.allowanceChargeReasonField;
        }
        set {
            this.allowanceChargeReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public MultiplierFactorNumericType MultiplierFactorNumeric {
        get {
            return this.multiplierFactorNumericField;
        }
        set {
            this.multiplierFactorNumericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public SequenceNumericType SequenceNumeric {
        get {
            return this.sequenceNumericField;
        }
        set {
            this.sequenceNumericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public AmountType2 Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public BaseAmountType BaseAmount {
        get {
            return this.baseAmountField;
        }
        set {
            this.baseAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public PerUnitAmountType PerUnitAmount {
        get {
            return this.perUnitAmountField;
        }
        set {
            this.perUnitAmountField = value;
        }
    }
}