//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uri.etsi.org/01903/v1.3.2#")]
public partial class CertIDType {
    
    private DigestAlgAndValueType certDigestField;
    
    private X509IssuerSerialType issuerSerialField;
    
    private string uRIField;
    
    /// <remarks/>
    public DigestAlgAndValueType CertDigest {
        get {
            return this.certDigestField;
        }
        set {
            this.certDigestField = value;
        }
    }
    
    /// <remarks/>
    public X509IssuerSerialType IssuerSerial {
        get {
            return this.issuerSerialField;
        }
        set {
            this.issuerSerialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
}