//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uri.etsi.org/01903/v1.3.2#")]
public partial class DocumentationReferencesType {
    
    private string[] documentationReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentationReference", DataType="anyURI")]
    public string[] DocumentationReference {
        get {
            return this.documentationReferenceField;
        }
        set {
            this.documentationReferenceField = value;
        }
    }
}