//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
[System.Xml.Serialization.XmlRootAttribute("EndorserParty", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", IsNullable=false)]
public partial class EndorserPartyType {
    
    private RoleCodeType roleCodeField;
    
    private SequenceNumericType sequenceNumericField;
    
    private PartyType partyField;
    
    private ContactType signatoryContactField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public RoleCodeType RoleCode {
        get {
            return this.roleCodeField;
        }
        set {
            this.roleCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public SequenceNumericType SequenceNumeric {
        get {
            return this.sequenceNumericField;
        }
        set {
            this.sequenceNumericField = value;
        }
    }
    
    /// <remarks/>
    public PartyType Party {
        get {
            return this.partyField;
        }
        set {
            this.partyField = value;
        }
    }
    
    /// <remarks/>
    public ContactType SignatoryContact {
        get {
            return this.signatoryContactField;
        }
        set {
            this.signatoryContactField = value;
        }
    }
}