//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uri.etsi.org/01903/v1.3.2#", IncludeInSchema=false)]
public enum ItemsChoiceType3 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    ArchiveTimeStamp,
    
    /// <remarks/>
    AttrAuthoritiesCertValues,
    
    /// <remarks/>
    AttributeCertificateRefs,
    
    /// <remarks/>
    AttributeRevocationRefs,
    
    /// <remarks/>
    AttributeRevocationValues,
    
    /// <remarks/>
    CertificateValues,
    
    /// <remarks/>
    CompleteCertificateRefs,
    
    /// <remarks/>
    CompleteRevocationRefs,
    
    /// <remarks/>
    CounterSignature,
    
    /// <remarks/>
    RefsOnlyTimeStamp,
    
    /// <remarks/>
    RevocationValues,
    
    /// <remarks/>
    SigAndRefsTimeStamp,
    
    /// <remarks/>
    SignatureTimeStamp,
}