//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SequenceNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResidentOccupantsNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReminderSequenceNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackSizeNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderQuantityIncrementNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderIntervalDaysNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiplierFactorNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumNumberNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumPaymentInstructionsNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumNumberNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumCopiesNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineNumberNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineCountNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FrozenPeriodDaysNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationSequenceNumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetYearNumericType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="NumericType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
public partial class NumericType1 : NumericType {
}