//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TierRatePercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetServicePercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SettlementDiscountPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReliabilityPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProgressPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PercentType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PenaltySurchargePercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParticipationPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartecipationPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(HumidityPercentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AirFlowPercentType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
public partial class PercentType : NumericType {
}