//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetCurrencyBaseRateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceCurrencyBaseRateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RateType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderableUnitFactorRateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationRateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmountRateType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
public partial class RateType : NumericType {
}