//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
[System.Xml.Serialization.XmlRootAttribute("MainCarriageShipmentStage", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", IsNullable=false)]
public partial class ShipmentStageType {
    
    private IDType idField;
    
    private TransportModeCodeType transportModeCodeField;
    
    private TransportMeansTypeCodeType transportMeansTypeCodeField;
    
    private TransitDirectionCodeType transitDirectionCodeField;
    
    private InstructionsType[] instructionsField;
    
    private PeriodType transitPeriodField;
    
    private TransportMeansType transportMeansField;
    
    private PersonType[] driverPersonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public IDType ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TransportModeCodeType TransportModeCode {
        get {
            return this.transportModeCodeField;
        }
        set {
            this.transportModeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TransportMeansTypeCodeType TransportMeansTypeCode {
        get {
            return this.transportMeansTypeCodeField;
        }
        set {
            this.transportMeansTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TransitDirectionCodeType TransitDirectionCode {
        get {
            return this.transitDirectionCodeField;
        }
        set {
            this.transitDirectionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Instructions", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public InstructionsType[] Instructions {
        get {
            return this.instructionsField;
        }
        set {
            this.instructionsField = value;
        }
    }
    
    /// <remarks/>
    public PeriodType TransitPeriod {
        get {
            return this.transitPeriodField;
        }
        set {
            this.transitPeriodField = value;
        }
    }
    
    /// <remarks/>
    public TransportMeansType TransportMeans {
        get {
            return this.transportMeansField;
        }
        set {
            this.transportMeansField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DriverPerson")]
    public PersonType[] DriverPerson {
        get {
            return this.driverPersonField;
        }
        set {
            this.driverPersonField = value;
        }
    }
}