//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
[System.Xml.Serialization.XmlRootAttribute("ApplicableTaxCategory", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", IsNullable=false)]
public partial class TaxCategoryType {
    
    private NameType1 nameField;
    
    private TaxExemptionReasonCodeType taxExemptionReasonCodeField;
    
    private TaxExemptionReasonType taxExemptionReasonField;
    
    private TaxSchemeType taxSchemeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public NameType1 Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TaxExemptionReasonCodeType TaxExemptionReasonCode {
        get {
            return this.taxExemptionReasonCodeField;
        }
        set {
            this.taxExemptionReasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TaxExemptionReasonType TaxExemptionReason {
        get {
            return this.taxExemptionReasonField;
        }
        set {
            this.taxExemptionReasonField = value;
        }
    }
    
    /// <remarks/>
    public TaxSchemeType TaxScheme {
        get {
            return this.taxSchemeField;
        }
        set {
            this.taxSchemeField = value;
        }
    }
}