//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
[System.Xml.Serialization.XmlRootAttribute("TaxSubtotal", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", IsNullable=false)]
public partial class TaxSubtotalType {
    
    private TaxableAmountType taxableAmountField;
    
    private TaxAmountType taxAmountField;
    
    private CalculationSequenceNumericType calculationSequenceNumericField;
    
    private TransactionCurrencyTaxAmountType transactionCurrencyTaxAmountField;
    
    private PercentType1 percentField;
    
    private BaseUnitMeasureType baseUnitMeasureField;
    
    private PerUnitAmountType perUnitAmountField;
    
    private TaxCategoryType taxCategoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TaxableAmountType TaxableAmount {
        get {
            return this.taxableAmountField;
        }
        set {
            this.taxableAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TaxAmountType TaxAmount {
        get {
            return this.taxAmountField;
        }
        set {
            this.taxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public CalculationSequenceNumericType CalculationSequenceNumeric {
        get {
            return this.calculationSequenceNumericField;
        }
        set {
            this.calculationSequenceNumericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public TransactionCurrencyTaxAmountType TransactionCurrencyTaxAmount {
        get {
            return this.transactionCurrencyTaxAmountField;
        }
        set {
            this.transactionCurrencyTaxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public PercentType1 Percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public BaseUnitMeasureType BaseUnitMeasure {
        get {
            return this.baseUnitMeasureField;
        }
        set {
            this.baseUnitMeasureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public PerUnitAmountType PerUnitAmount {
        get {
            return this.perUnitAmountField;
        }
        set {
            this.perUnitAmountField = value;
        }
    }
    
    /// <remarks/>
    public TaxCategoryType TaxCategory {
        get {
            return this.taxCategoryField;
        }
        set {
            this.taxCategoryField = value;
        }
    }
}