namespace UblTr.Common
{
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VesselNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnicalNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StreetNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoamingPartnerNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetailEventNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameType1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiddleNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HolderNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FirstNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CitySubdivisionNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CityNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoryNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildingNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BrandNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlockNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalStreetNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionAgencyNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XPathType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkPhaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WarrantyInformationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueQualifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateToolVersionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateToolType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateProcessType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportationServiceDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportUserSpecialTermsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportUserRemarksType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportServiceProviderSpecialTermsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportServiceProviderRemarksType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TradingRestrictionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TitleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimingComplaintType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimezoneOffsetType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeAmountType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TierRangeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TestMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelephoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelefaxType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsSupplyTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsServiceCategoryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsServiceCallType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnicalCommitteeDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxExemptionReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TariffDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SummaryDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialTransportRequirementsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialTermsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialServiceInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SignatureMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShipsRequirementsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShippingMarksType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceNumberCalledType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SealingPartyTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoomType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResolutionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResidenceTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReplenishmentOwnerDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemarksType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectionNoteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegulatoryDomainType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationNationalityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RankType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PurposeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrizeDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriorityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrintQualifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceRevisionFormulaDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceChangeReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousMeterReadingMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostboxType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostalZoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlotIdentificationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlacardNotationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlacardEndorsementType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneNumberType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonalSituationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentOrderReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentNoteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PayerReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PayPerViewType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PasswordType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartyTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackingMaterialType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OutstandingReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherInstructionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationDepartmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderableUnitType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionsDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OneTimeChargeTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NegotiationDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameSuffixType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MovieTitleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MonetaryScopeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumImprovementBidType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterReadingTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterReadingCommentsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterNumberType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterConstantType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkCareType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkAttentionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LowTendersDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LossRiskType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LimitationDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegalReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestMeterReadingMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeywordType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JustificationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JustificationDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobTitleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoicingPartyReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstructionNoteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InhouseMailType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HeatingTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HaulageInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HashAlgorithmMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HandlingInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FundingProgramType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FrequencyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForwarderServiceInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FloorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FeeDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpressionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExemptionReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExclusionReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectronicMailType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectronicDeviceDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DutyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentStatusReasonDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentHashType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistrictType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DemurrageInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataSendingCapabilityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DamageRemarksType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomsClearanceServiceInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrentChargeTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountrySubentityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrectionTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractSubdivisionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionLevelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumersEnergyLevelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionsDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyLegalFormType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CommentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacteristicsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChannelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeConditionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificateTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CarrierServiceInstructionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CanonicalizationMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidateStatementType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancellationNoteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationExpressionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuyerReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildingNumberType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BirthplaceNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BackorderReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardingCriterionDescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApprovalStatusType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AllowanceChargeReasonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgencyNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalInformationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalConditionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityTypeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountingCostType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcceptedVariantsDescriptionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2")]
    public partial class TextType
    {

        private string languageIDField;

        private string languageLocaleIDField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string languageID
        {
            get
            {
                return this.languageIDField;
            }
            set
            {
                this.languageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
        public string languageLocaleID
        {
            get
            {
                return this.languageLocaleIDField;
            }
            set
            {
                this.languageLocaleIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}